name: hotel_booking_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.8.0
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  http: ^0.13.3
  flash: ^3.1.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  amadeus_flutter: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/BuscaHoteis.png
    - lib/assets/fallback_image.jpg
